config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get "/auth/twitter", as: :login
  get "/auth/twitter/callback", to: "sessions#create"
  get "logout", to: "sessions#destroy"
  resources :users, only: [:show]
  resources :tweets, only: [:new, :create]
  resources :favorites, only: [:create, :destroy]
  resources :retweets, only: [:create]
  post "unfollow", as: :unfollow, to: "users#unfollow"
end

app/models/tweet.rb
class Tweet < OpenStruct
  def retweeted?
    retweeted
  end

  def favorited?
    favorited
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  def service
    @service ||= TwitterService.new(self)
  end

  def self.banner_converter(auth_info)
    auth_info.extra.raw_info.profile_banner_url + "/600x200"
  end

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.name               = auth_info.extra.raw_info.name
      new_user.screen_name        = auth_info.extra.raw_info.screen_name
      new_user.banner_image       = User.banner_converter(auth_info)
      new_user.profile_image      = auth_info.info.image
      new_user.oauth_token        = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
  end

  delegate :unfollow, :post, :retweet, :favorite, :unfavorite, to: :service
end

app/models/user_presenter.rb
class UserPresenter
  attr_reader :user, :service

  def initialize(user)
    @user = user
    @service = TwitterService.new(user)
  end

  def banner_image
    user.banner_image
  end

  def profile_image
    user.profile_image
  end

  def name
    user.name
  end

  def screen_name
    user.screen_name
  end

  def tweets
    service.tweets.map { |tweet| Tweet.new(tweet.to_h) }
  end

  def tweet_count
    tweets.count
  end

  def followers
    service.followers
  end

  def following
    service.following
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    current_user.favorite(params[:uid])
    redirect_to current_user
  end

  def destroy
    current_user.unfavorite(params[:uid])
    redirect_to current_user
  end
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
  def create
    current_user.retweet(params[:uid])
    redirect_to current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to user
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def new
  end

  def create
    current_user.post(params[:text])
    redirect_to current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = UserPresenter.new(current_user)
  end

  def unfollow
    current_user.unfollow(params[:screen_name])
    redirect_to current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<% if flash[:errors] %>
 <div class="alert alert-danger text-center"><%= flash[:errors] %></div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-success text-center"><%= flash[:notice] %></div>
<% end %>

<nav id="my-navbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div id="my-navbar" class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href= <%= root_path %> >Tribes</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <li><%= link_to "Hello, #{current_user.name}", user_path(current_user.id) %></li>
                <li><%= link_to 'Logout', logout_path %></li>
              <% else %>
                <li><%= link_to "Login", login_path %></li>
            <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tribes</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>
  <%= yield %>

</body>
</html>

app/views/tweets/_new.html.erb
<%= bootstrap_form_tag url: "/tweets" do |f| %>
  <%= f.text_field :text %>
  <%= submit_tag "Tweet", class: "btn btn-sm btn-primary" %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="well col-md-12">
  <div class="col-md-2">
    <%= image_tag tweet.user[:profile_image_url] %>
    <br>
    <div class="unfollow unfollow-<%= tweet.id %>">
      <% unless tweet.user[:id] == current_user.uid.to_i %>
        <%= button_to "Unfollow", unfollow_path(tweet.user), class: "btn
        btn-sm btn-primary" %>
      <% end %>
    </div>
  </div>
  <div class="row tweet-content col-md-10"><strong><%= tweet.user[:name] %></strong> @<%= tweet.user[:screen_name] %>
    <br>
    <%= tweet.text %>
    <div class="row">
      <div class="col-md-4 retweet-<%= tweet.id %>">
        <% unless tweet.retweeted? || tweet.user[:id] == current_user.uid.to_i %>
          <%= button_to retweets_path(uid: tweet.id), class: "btn
          btn-sm btn-primary", id: "retweet-#{tweet.id}" do %>
            <span class="glyphicon glyphicon-retweet"></span> <%= tweet.retweet_count %>
          <% end %>
        <% else %>
          <span class="glyphicon glyphicon-retweet" style="color:blue"></span> <%= tweet.retweet_count %>
        <% end %>
      </div>
      <div class="col-md-4 favorite-<%= tweet.id %>">
        <% unless tweet.favorited? %>
          <%= button_to favorites_path(uid: tweet.id), class: "btn
          btn-sm btn-primary", id: "favorite-#{tweet.id}" do %>
            <span class="glyphicon glyphicon-star"></span> <%= tweet.favorite_count %>
          <% end %>
        <% else %>
          <%= button_to favorite_path(uid: tweet.id), class: "btn
          btn-sm btn-primary", id: "unfavorite-#{tweet.id}", method: :delete do %>
            <span class="glyphicon glyphicon-star"></span> <%= tweet.favorite_count %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<br>

app/views/users/show.html.erb
<br>
<br>
<br>
<div class='container-fluid page-content'>
  <div class="row">
    <div class="col-md-3">
      <div class="panel-body gh-address-box">
        <div class="row">
          <div class="col-md-12 ">
            <%= image_tag(@user.banner_image, class: "img-responsive col-centered") %>
            <div class="profile-avatar">
              <%= image_tag(@user.profile_image, class: "img-responsive col-centered") %>
            </div>
            <div class="profile-text">
              <strong><%= @user.name %></strong><br>
              @<%= @user.screen_name %>
            </div>
            <div class="col-md-4">
              <span class="stat-text">TWEETS</span><br>
              <span class="stat-number"><%= @user.tweet_count %></span>
            </div>
            <div class="col-md-4">
              <span class="stat-text">FOLLOWING</span><br>
              <span class="stat-number"><%= @user.following %></span>
            </div>
            <div class="col-md-4">
              <span class="stat-text">FOLLOWERS</span><br>
              <span class="stat-number"><%= @user.followers %></span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel-body gh-main-content">
          <div class="col-md-12">
            <div class="joblist">
                <%= render partial: "/tweets/new" %>
                <br>
               <%= render partial: "/tweets/tweet", collection: @user.tweets %>
            </div>
          </div>
        </div>
      </div>
    <div class="col-md-3">
      <div class="panel-body">
      </div>
    </div>
  </div>
</div>

  <!-- jQuery -->
  <script src="js/jquery.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Tribes - Find Your Tribe</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="css/animate.min.css" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="css/creative.css" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1 class="hero-text">Start Your Tribe</h1>
                <hr>
                <p>You already have a Tribe. Its time to make it official.</p>
                <%= link_to "Login with Twitter", login_path, class:"btn btn-primary btn-xl page-scroll" %>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">We've got what you need!</h2>
                    <hr class="light">
                    <p class="text-faded">Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!</p>
                    <a href="#" class="btn btn-default btn-xl">Get Started!</a>
                </div>
            </div>
        </div>
    </section>

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">At Your Service</h2>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-diamond wow bounceIn text-primary"></i>
                        <h3>Sturdy Templates</h3>
                        <p class="text-muted">Our templates are updated regularly so they don't break.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-paper-plane wow bounceIn text-primary" data-wow-delay=".1s"></i>
                        <h3>Ready to Ship</h3>
                        <p class="text-muted">You can use this theme as is, or you can make changes!</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-newspaper-o wow bounceIn text-primary" data-wow-delay=".2s"></i>
                        <h3>Up to Date</h3>
                        <p class="text-muted">We update dependencies to keep things fresh.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-heart wow bounceIn text-primary" data-wow-delay=".3s"></i>
                        <h3>Made with Love</h3>
                        <p class="text-muted">You have to make your websites with love these days!</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter">
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="img/portfolio/1.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="img/portfolio/2.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="img/portfolio/3.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="img/portfolio/4.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="img/portfolio/5.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-4 col-sm-6">
                    <a href="#" class="portfolio-box">
                        <img src="img/portfolio/6.jpg" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    Category
                                </div>
                                <div class="project-name">
                                    Project Name
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>Free Download at Start Bootstrap!</h2>
                <a href="#" class="btn btn-default btn-xl wow tada">Download Now!</a>
            </div>
        </div>
    </aside>

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x wow bounceIn"></i>
                    <p>123-456-6789</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                    <p><a href="mailto:your-email@your-domain.com">feedback@startbootstrap.com</a></p>
                </div>
            </div>
        </div>
    </section>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    <script src="js/jquery.fittext.js"></script>
    <script src="js/wow.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/creative.js"></script>

</body>

</html>